image: node:20

stages:
  - install-and-test
  - generate-allure-report

install_dependencies:
  stage: install-and-test
  script:
    - npm install
    - apt-get update
    - apt-get install -y libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libnss3-dev libxrandr2 libgbm1 libasound2
    - npm run wdio

generate-allure-result:
  stage: generate-allure-report
  image: pradapjackie/allure-reports-generation:1.0
  artifacts:
    paths:
      - allure-report
    when: always
    expire_in: 1 days
  script:
    - allure generate allure-results --clean -o allure-report
  when: always
  allow_failure: true
