stages:
  - install-and-test
  - generate-allure-report
  - send-slack-notification

install_dependencies:
  stage: install-and-test
  image: node:20
  artifacts:
    paths:
      - allure-results
    when: always
    expire_in: 1 days
  script:
    - apt-get update
    - apt-get install -y --no-install-recommends wget gnupg2
    - wget -qO - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
    - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
    - apt-get update
    - apt-get install -y google-chrome-stable libnss3 libatk-bridge2.0-0 libx11-xcb1 libxcomposite1 libxcursor1 libxdamage1 libxi6 libxtst6 libxrandr2 libgbm1 libasound2
    - npm install
    - npm run wdio

generate-allure-result:
  stage: generate-allure-report
  image: pradapjackie/allure-reports-generation:1.0
  artifacts:
    paths:
      - allure-report
      - allure-results
    when: always
    expire_in: 1 days
  script:
    - allure generate allure-results --clean -o allure-report
  when: always
  allow_failure: true

send-slack-notification:
  stage: notify
  image: node:18
  script:
    - npm install axios
    - node send_slack_notification.js
  dependencies:
    - generate-allure-result
