image: node:20

stages:
  - install-and-test
  - generate-allure-report

install_dependencies:
  stage: install-and-test
  script:
    - npm install
    - npm run wdio

generate-allure-result:
  stage: generate-allure-report
  image: pradapjackie/allure-reports-generation:1.0
  artifacts:
    paths:
      - allure-results
      - allure-report
    when: always
    expire_in: 1 days
  script:
    - allure generate allure-results --clean -o allure-report
  when: always
  allow_failure: true
