# bitbucket-pipelines.yml

image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Install Dependencies
        script:
          - apt-get update && apt-get install -y nodejs npm
          - apt-get install -y chromium-browser chromium-chromedriver
          - ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver
          - npm install

    - step:
        name: Run WebDriverIO Tests
        script:
          - npm test

    - step:
        name: Generate Allure Report
        image: pradapjackie/allure-reports-generation:1.0
        artifacts:
          paths:
            - allure-results
            - allure-report
        when: always
        expire_in: 1 days
        script:
          - allure generate allure-results --clean -o allure-report
        allow_failure: true
        rules:
          - when: always
