image: ubuntu:latest

pipelines:
  default:
    - step:
        name: Install Dependencies
        script:
          - apt-get update && apt-get install -y \
            curl \
            libglib2.0-0 \
            chromium-browser \
            chromium-chromedriver
          - curl -sL https://deb.nodesource.com/setup_16.x | bash -
          - apt-get install -y nodejs
          - npm install
          - npm run wdio

