image: node:18

pipelines:
  default:
    - step:
        name: Build
        caches:
          - node
        script:
          - npm install
          - npm run wdio
        artifacts:
          - reports/allure/allure-report/*