image: ianwalter/puppeteer:latest

pipelines:
  default:
    - step:
        name: Install Dependencies and Run Tests
        caches:
          - node
        script:
          - npm install
          - npm run wdio 
          
    - step:
        name: Generate Allure Report
        image: pradapjackie/allure-reports-generation:1.0
        artifacts:
          paths:
            - allure-results
            - allure-report
        when: always
        expire_in: 1 days
        script:
          - allure generate allure-results --clean -o allure-report
        allow_failure: true
        rules:
          - when: always
