name: Webdriver Automation
on:
  push:
    branches:
      - main
  pull_request:
    branches:    
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install
          run: npm install
        - name: Test
          run: npm run wdio
          continue-on-error: true
        - name: Generate Allure report
          run: npm run allure-generate
          continue-on-error: true
        - uses: actions/upload-artifact@v3
          with:
            name: allureReport
            path: ./allure-report
