name: Test JMeter Action

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  action_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Run JMeter Action on a test
        uses: rbhadti94/apache-jmeter-action@v0.5.0
        with:
          testFilePath: country-list.jmx
          outputReportsFolder: reports/
          args: "--loglevel INFO -Jthreads=2 -Jrampup=1 -Jloops=1"

      - uses: actions/upload-artifact@v1
        with:
          name: jmeter-test-results
          path: reports/
